export class PhoneModel {
    announced: string;
    audioJack: string;
    bands2g: string;
    bands3g: string;
    bands4g: string;
    battery: string;
    bluetooth: string;
    chipset: string;
    colors: string;
    cpu: string;
    dimensions: string;
    displayResolution: string;
    displaySize: string;
    displayType: string;
    edge: string;
    gprs: string;
    gps: string;
    gpu: string;
    id: number
    imgUrl: string;
    internalMemory: string;
    memoryCard: string;
    name: string;
    networkSpeed: string;
    networkTechnology: string;
    os: string;
    priceEur: number
    primaryCamera: string;
    ram: string;
    secondaryCamera: string;
    sensors: string;
    sim: string;
    speaker: string;
    status: string;
    usb: string;
    weightG: string;
    wlan: string;
}